"use client";

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { ChevronDown, HelpCircle } from "lucide-react";

const faqs = [
  {
    question: "Is TermsZipp really free?",
    answer: "Yes! Our basic document generator is completely free. You can generate previews of any legal document at no cost. For full document access, export options, and additional features, we offer affordable Pro and Premium plans."
  },
  {
    question: "Are these documents legally binding?",
    answer: "The documents generated by TermsZipp are templates designed to cover common legal requirements. However, we strongly recommend having any legal document reviewed by a qualified attorney before publishing it on your website, as legal requirements vary by jurisdiction and business type."
  },
  {
    question: "What's the difference between free and paid plans?",
    answer: "Free users can preview approximately 50% of any generated document. Pro and Premium subscribers get full document access, Word and PDF export options, the ability to save documents to their dashboard, and no TermsZipp branding in exports."
  },
  {
    question: "Can I edit the generated documents?",
    answer: "Absolutely! All documents can be customized to fit your specific needs. You can export them in various formats and make any changes necessary for your business."
  },
  {
    question: "Are the documents GDPR and CCPA compliant?",
    answer: "Our document templates include sections for GDPR (EU) and CCPA (California) compliance. You can enable or disable these sections based on your audience. However, compliance ultimately depends on your specific data practices, so we recommend legal review."
  },
  {
    question: "How often should I update my legal documents?",
    answer: "We recommend reviewing your legal documents at least annually, or whenever you make significant changes to your data collection practices, business model, or when new regulations come into effect."
  },
  {
    question: "Can I use these documents for my client's websites?",
    answer: "Yes! Our Premium plan is designed for agencies and freelancers who need to generate documents for multiple clients. You can generate unlimited documents and customize them for each client."
  },
  {
    question: "What export formats are available?",
    answer: "Pro and Premium users can export documents as HTML (for direct embedding on your site), Markdown, Word (.docx), and PDF formats. Free users can copy the preview text."
  },
  {
    question: "Do you offer refunds?",
    answer: "Yes, we offer a 14-day money-back guarantee on all paid plans. If you're not satisfied, contact us within 14 days of your purchase for a full refund."
  },
  {
    question: "How do I add the documents to my website?",
    answer: "After generating your document, you can either: 1) Copy the HTML and paste it into a page on your website, 2) Download the file and upload it to your site, or 3) Link to a hosted version if you're on our Premium plan."
  },
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <div className="bg-white border-b">
        <div className="container mx-auto px-4 py-16 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-cyan-50 border border-cyan-200 mb-6">
            <HelpCircle className="h-4 w-4 text-cyan-600" />
            <span className="text-sm font-medium text-cyan-700">Help Center</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Frequently Asked Questions
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Got questions? We've got answers. If you can't find what you're looking for, 
            feel free to contact us.
          </p>
        </div>
      </div>

      {/* FAQ List */}
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, index) => (
            <Card 
              key={index}
              className={`overflow-hidden transition-all ${openIndex === index ? 'ring-2 ring-cyan-200' : ''}`}
            >
              <button
                className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-slate-50 transition-colors"
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
              >
                <span className="font-medium pr-4">{faq.question}</span>
                <ChevronDown 
                  className={`h-5 w-5 text-muted-foreground shrink-0 transition-transform ${
                    openIndex === index ? 'rotate-180' : ''
                  }`} 
                />
              </button>
              {openIndex === index && (
                <div className="px-6 pb-4">
                  <p className="text-muted-foreground">{faq.answer}</p>
                </div>
              )}
            </Card>
          ))}
        </div>

        {/* Still have questions */}
        <div className="max-w-3xl mx-auto mt-12 text-center">
          <Card className="p-8 bg-gradient-to-br from-cyan-50 to-teal-50 border-cyan-200">
            <h2 className="text-xl font-semibold mb-2">Still have questions?</h2>
            <p className="text-muted-foreground mb-4">
              Can't find the answer you're looking for? Our team is here to help.
            </p>
            <a 
              href="/contact" 
              className="inline-flex items-center justify-center px-6 py-2 rounded-lg btn-gradient text-white font-medium"
            >
              Contact Us
            </a>
          </Card>
        </div>
      </div>
    </div>
  );
}
